import type { Metadata } from "next";
import "./globals.css";
// import { fontSofia, fontSpace } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "Riko Fernanda Saputra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
